openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /products:
    get:
      operationId: getAllProducts
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
          description: OK
      tags:
      - product-controller
      x-accepts: '*/*'
    post:
      operationId: addProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
          description: OK
      tags:
      - product-controller
      x-content-type: application/json
      x-accepts: '*/*'
  /products/{id}:
    delete:
      operationId: deleteProduct
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: OK
      tags:
      - product-controller
      x-accepts: application/json
components:
  schemas:
    Product:
      example:
        name: name
        description: description
        id: 0
        extId: extId
      properties:
        id:
          format: int64
          type: integer
        extId:
          type: string
        name:
          type: string
        description:
          type: string
      type: object

