name: Java CI with Gradle

on:
  push:
    branches:
      - '**'  # Triggers on every branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test the backend
      run: ./gradlew :spring-boot-app:build
    - name: Build the frontend
      run: ./gradlew :frontend:ngBuild
    - name: Test the frontend
      run: ./gradlew :frontend:ngTest
